### ISSUE TITLE
sidebar not open

### ISSUE THREAD

**Issue by nguyentranchung** [tailwindadmin/admin#1]
![image](https://user-images.githubusercontent.com/9611224/52387995-b680c500-2acf-11e9-9eef-41756da53dd1.png)

**Comment by riteshsingh1** [comment]
Hi Can You provide more details, like broswer and maybe paste a scrrenshot?

**Comment by riteshsingh1** [comment]
Unable to reproduce this issue, hence closing..

**Comment by nguyentranchung** [comment]
I run it on brave browser, it worked on chrome

**Comment by riteshsingh1** [comment]
Working on brave browser also, hence closing this issue.
