### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by azrahn** [tailwindadmin/admin#11]

**Comment by riteshsingh1** [comment]
No, tailwind version update is in progress, with grid and all.

**Comment by rhoyle** [comment]
How much longer this is a good template it just needs to be updated like to tailwindcss 2.2.19 Also I want to use this on a Laravel 8.71.0 and the upcoming 9.0 With PHP 8.0 and above 

Having trouble with the menu icons not showing up right.
I tried updating npm but got errors
