### ISSUE TITLE
Looking for the preprocessed Tailwind version.

### ISSUE THREAD

**Issue by davidteren** [tailwindadmin/admin#2]
This is a really nice Admin Dashboard. Would really like to use this.
However  it looks like `index.html` was processed and can no longer be developed using preprocessed Tailwind?

Seems it happened in this commit. https://github.com/tailwindadmin/admin/commit/b14b669d1808ee178bd7828ae9a90a2beb2bdfa4

Is there a current preprocessed version available?
Or am I missing something?

**Comment by riteshsingh1** [comment]
This whole template is based on webpack, you can clone and make changes to tailwind.js for your configuration and then rebuild using, yarn dev or npm run dev.

Please tell me if that solves your issue.

**Comment by davidteren** [comment]
I'm using [Tailwind in Ruby on Rails 6 via Webpacker ](https://github.com/davidteren/rails_6_with_tailwind_css)(Rails Webpack Preprocessor) 
So in dev mode it expects the Tailwind classes. Bringing `style.css` into the mix kind messes with stuff unless I need to figure that out.

Here I use a pre https://github.com/tailwindadmin/admin/commit/b14b669d1808ee178bd7828ae9a90a2beb2bdfa4 commit `index.html`
![01-pre_basic_layout_commit](https://user-images.githubusercontent.com/5962867/55666906-674bdc00-5855-11e9-99c3-a46e9b68e87c.png)

And here I use the latest commits `index.thml`
![002-latest](https://user-images.githubusercontent.com/5962867/55666914-99f5d480-5855-11e9-9cf4-f21cb4985ecf.png)

**Comment by riteshsingh1** [comment]
You need to replace your app/javascript/css/tailwind.js with https://github.com/tailwindadmin/admin/blob/master/tailwind.js

because this one is having some color combinations and one plugin.
Try this one revert if it works.

**Comment by davidteren** [comment]
Thanks it's working now. Well almost. I get a `Error: Cannot find module 'tailwindcss-tables'
I have installed `yarn add tailwindcss-tables` 
If I remove `require('tailwindcss-tables')(),` the page loads.

![image](https://user-images.githubusercontent.com/5962867/55730626-e89f9c00-5a18-11e9-940a-2e78d118f2b6.png)

**Comment by riteshsingh1** [comment]
try this  instead `require('tailwindcss-tables')()` give full path to node_modules `require('/node_modules/tailwindcss-tables')()`

**Comment by davidteren** [comment]
It's working now. Thanks so much for your efforts.

**Comment by riteshsingh1** [comment]
I am glad this issue is fixed, so closing the issue now...
